inherit_gem:
  ezcater_rubocop: conf/rubocop_gem.yml

AllCops:
  TargetRubyVersion: 2.6

Lint/UnneededCopDisableDirective:
  Exclude:
    - "lib/generators/sidekiq_publisher/templates/create_sidekiq_publisher_jobs.rb"
