name: sidekiq-publisher
owner: core-platform
skip_production_deploy: true
pipeline:
  skip_push_image: true
deployables: []
tests:
  primary:
  - name: sidekiq-publisher
    build: .
    command: tail -f /dev/null
    junit: rspec.xml
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: ezcater
      REDIS_URL: redis://localhost:6379/1
  services:
  - name: postgres
    image: postgres:13.2-alpine
    environment:
      POSTGRES_DATABASE: sidekiq_publisher_test
      POSTGRES_PASSWORD: password
      POSTGRES_USER: ezcater
  - name: redis
    image: redis:5.0.9-alpine
  steps:
  - run:
      test: bundle
      command: in_all_rubies.sh bundle
  - run:
      test: rubocop
      command: in_latest_ruby.sh bundle exec rubocop
  - run:
      test: bundle-appraisals
      command: in_all_rubies.sh bundle exec appraisal install
  # the appraisals for Rails 5.2 are disabled for now; if we want to keep them, we need to use
  # an older version of the multiruby image, because 5.2 only supports up through ruby 2.6:
  # - run:
  #     test: rspec-rails-5.2-sidekiq-5.0
  #     command: in_all_rubies.sh bundle exec appraisal rails-5.2-sidekiq-5.0 rspec --format RspecJunitFormatter --format progress
  # - run:
  #     test: rspec-rails-5.2-sidekiq-5.1
  #     command: in_all_rubies.sh bundle exec appraisal rails-5.2-sidekiq-5.1 rspec --format RspecJunitFormatter --format progress
  # - run:
  #     test: rspec-rails-5.2-sidekiq-5.2
  #     command: in_all_rubies.sh bundle exec appraisal rails-5.2-sidekiq-5.2 rspec --format RspecJunitFormatter --format progress
  # - run:
  #     test: rspec-rails-5.2-sidekiq-6.0
  #     command: in_all_rubies.sh bundle exec appraisal rails-5.2-sidekiq-6.0 rspec --format RspecJunitFormatter --format progress
  # - run:
  #     test: rspec-rails-5.2-sidekiq-6.1
  #     command: in_all_rubies.sh bundle exec appraisal rails-5.2-sidekiq-6.1 rspec --format RspecJunitFormatter --format progress
  # - run:
  #     test: rspec-rails-5.2-sidekiq-6.2
  #     command: in_all_rubies.sh bundle exec appraisal rails-5.2-sidekiq-6.2 rspec --format RspecJunitFormatter --format progress
  # - run:
  #     test: rspec-rails-5.2-sidekiq-6.3
  #     command: in_all_rubies.sh bundle exec appraisal rails-5.2-sidekiq-6.3 rspec --format RspecJunitFormatter --format progress
  - run:
      test: rspec-rails-6.0-sidekiq-5.2
      command: in_all_rubies.sh bundle exec appraisal rails-6.0-sidekiq-5.2 rspec --format RspecJunitFormatter --format progress
  - run:
      test: rspec-rails-6.0-sidekiq-6.0
      command: in_all_rubies.sh bundle exec appraisal rails-6.0-sidekiq-6.0 rspec --format RspecJunitFormatter --format progress
  - run:
      test: rspec-rails-6.0-sidekiq-6.1
      command: in_all_rubies.sh bundle exec appraisal rails-6.0-sidekiq-6.1 rspec --format RspecJunitFormatter --format progress
  - run:
      test: rspec-rails-6.0-sidekiq-6.2
      command: in_all_rubies.sh bundle exec appraisal rails-6.0-sidekiq-6.2 rspec --format RspecJunitFormatter --format progress
  - run:
      test: rspec-rails-6.0-sidekiq-6.3
      command: in_all_rubies.sh bundle exec appraisal rails-6.0-sidekiq-6.3 rspec --format RspecJunitFormatter --format progress
  - run:
      test: rspec-rails-6.1-sidekiq-5.2
      command: in_all_rubies.sh bundle exec appraisal rails-6.1-sidekiq-5.2 rspec --format RspecJunitFormatter --format progress
  - run:
      test: rspec-rails-6.1-sidekiq-6.0
      command: in_all_rubies.sh bundle exec appraisal rails-6.1-sidekiq-6.0 rspec --format RspecJunitFormatter --format progress
  - run:
      test: rspec-rails-6.1-sidekiq-6.1
      command: in_all_rubies.sh bundle exec appraisal rails-6.1-sidekiq-6.1 rspec --format RspecJunitFormatter --format progress
  - run:
      test: rspec-rails-6.1-sidekiq-6.2
      command: in_all_rubies.sh bundle exec appraisal rails-6.1-sidekiq-6.2 rspec --format RspecJunitFormatter --format progress
  - run:
      test: rspec-rails-6.1-sidekiq-6.3
      command: in_all_rubies.sh bundle exec appraisal rails-6.1-sidekiq-6.3 rspec --format RspecJunitFormatter --format progress
