name: CI
on:
  push:
    branches: [ main ]
  pull_request:

env:
  app: sidekiq_publisher

jobs:
  # lint:
  #   name: Lint (Ruby ${{ matrix.ruby }})
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       ruby: [ '2.6', '2.7', '3.0', '3.1', '3.2' ]

  #   steps:
  #     - name: Checkout the code
  #       uses: actions/checkout@v3

  #     - name: Install Ruby ${{ matrix.ruby }}
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: ${{ matrix.ruby }}
  #         bundler-cache: true

  #     - name: Install dependencies
  #       run: bundle install

  #     - name: Run Rubocop
  #       run: bundle exec rubocop

  test:
    name: Test (${{ matrix.gemfile }})
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/sidekiq_publisher_test
      PGHOST: 127.0.0.1
      PGUSER: postgres
      REDIS_URL: redis://localhost:6379
      RAILS_ENV: test

    services:
      postgres:
        image: postgres:12.6
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_DB: sidekiq_publisher_test
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis:6.0.20-alpine
        options: >-
          --health-cmd "redis-cli ping | grep PONG"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run Rspec
        run: |
          bundle exec appraisal install
          bundle exec appraisal rspec
